title: curios
description: weird
theme: just-the-docs

url: https://nikmeiser.github.io

plugins:
  - jekyll-feed

aux_links:
  nikmeiser.github.io: https://nikmeiser.github.io

nav:
  - title: "Home"
    url: /
  - title: "Blog"
    url: /blog/
    children:
    

color_scheme: light_pink
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/nikmeiser/nikmeiser.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
